docs: add login and user mode docs
graasp/graasp-desktop pull request #316
Opened 2020-08-24 12:48 UTC by pyphilia

Resolve issue #218 and #217 with docs describing our decisions for the user login and the user modes.

2020-08-30 23:06 UTC, juancarlosfarah requested changes
Thanks for this! Only minor changes. Can merge after.

2020-08-30 23:06 UTC, juancarlosfarah commented on docs/authentication/authenticaton-proposals.md
> +session.
Remove line break here, no?

2020-08-30 23:06 UTC, juancarlosfarah commented on docs/authentication/userMode.md
> +|        Visit a Space        |   yes    |               yes                |
Capitalisation consistency

2020-08-30 23:06 UTC, juancarlosfarah commented
@hasanagh, this PR will be useful for you to see.

2020-08-31 13:30 UTC, hasanagh commented
> @hasanagh, this PR will be useful for you to see.

Thanks! I checked it!

2020-08-31 15:19 UTC, merged