354/update and fix
graasp/graasp-desktop pull request #358
Opened 2020-11-17 12:55 UTC by pyphilia

close #354

2020-11-17 16:39 UTC, juancarlosfarah requested changes
Looks good! Just some minor changes.

2020-11-17 16:39 UTC, juancarlosfarah commented on scripts/setup.js
> +  HELLO: 'er',
Do we really need these?

2020-11-17 16:39 UTC, juancarlosfarah commented on src/components/common/WelcomeContent.js
> -          disableElevation
Is this no longer needed?

2020-11-17 16:39 UTC, juancarlosfarah commented on src/components/dashboard/ActionBarChart.js
> +        primary: PropTypes.shape().isRequired,
Missing `{}`?

2020-11-17 16:39 UTC, juancarlosfarah commented on src/components/dashboard/ActionLineChart.js
> +        primary: PropTypes.shape().isRequired,
Missing `{}`?

2020-11-18 13:18 UTC, pyphilia commented
Thank you for your review, I took this opportunity to close #348 as well.

2020-11-19 15:27 UTC, juancarlosfarah approved these changes

2020-11-19 15:27 UTC, merged